# Generated by Django 5.2.12 on 2026-04-17 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_role",
                    models.CharField(
                        choices=[
                            ("programmer", "Програміст"),
                            ("manager", "Менеджер"),
                            ("analyst", "Аналітик"),
                            ("student", "Студент"),
                            ("teacher", "Викладач"),
                            ("other", "Інше"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "usage_purpose",
                    models.CharField(
                        choices=[
                            ("personal", "Особиста"),
                            ("commercial", "Комерційна"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
