# Generated by Django 5.2.12 on 2026-04-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="terms",
            field=models.BooleanField(default=False),
        ),
    ]
